version: "3.9"
services:
  backend:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app # Mount backend code for hot reloading
    ports:
      - "8080:8080"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend/.
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    volumes:
      - ./frontend:/app # Mount frontend code for hot reloading
    depends_on:
      - backend
    networks:
      - app_network

# Define the custom network
networks:
  app_network:
    driver: bridge
