name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCLOUD_AUTH_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker

    - name: Deploy Frontend and Backend
      run: make deploy
