name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  deploy:
    name: Deploy new BE and FE images to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_AUTH_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: fantasy-trade-targets

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker

    - name: Deploy Frontend and Backend
      run: |
        set -x
        make deploy
